import os
import sys
from dataclasses import dataclass
from pathlib import Path

from tray_icon_support import get_tray_icon_pyinstaller_args


FOLDER_ICON_PREFIX = ".exe_builder_folder_icon_"
FOLDER_ICON_SUFFIX = ".ico"
FOLDER_ICON_CACHE_DIR_NAME = ".exe_builder_folder_icons"
DESKTOP_INI_NAME = "desktop.ini"
DESKTOP_INI_MARKER = "Generated by Win-11-Python-EXE-Builder"


@dataclass(frozen=True)
class BuildIconContract:
    icon_path: str

    @property
    def pyinstaller_args(self):
        if not self.icon_path:
            return ["--icon=NONE"]
        return [*get_tray_icon_pyinstaller_args(self.icon_path), "--icon", self.icon_path]


def resolve_build_icon_contract(icon_path):
    icon = (icon_path or "").strip()
    return BuildIconContract(os.path.normpath(icon) if icon else "")


def clear_output_folder_icon_metadata(output_folder):
    folder = Path(output_folder) if output_folder else None
    if folder is None or not folder.is_dir():
        return False

    removed = _remove_generated_folder_icon_files(folder)
    removed = _remove_previous_cached_folder_icon(folder) or removed
    desktop_ini = folder / DESKTOP_INI_NAME
    if _is_generated_desktop_ini(desktop_ini):
        try:
            _set_windows_attributes(desktop_ini, hidden=False, system=False)
            desktop_ini.unlink()
            removed = True
        except OSError:
            pass

    _set_windows_attributes(folder, readonly=False, system=False)
    return removed


def _generated_cached_icon_path_from_desktop_ini(folder):
    desktop_ini = folder / DESKTOP_INI_NAME
    if not _is_generated_desktop_ini(desktop_ini):
        return None

    try:
        for line in desktop_ini.read_text(encoding="utf-8", errors="ignore").splitlines():
            if not line.lower().startswith("iconresource="):
                continue
            value = line.split("=", 1)[1].split(",", 1)[0].strip()
            if not value:
                return None
            path = Path(value)
            if not path.is_absolute():
                path = folder / value.replace("\\", os.sep)
            path = path.resolve()
            cache_dir = (folder.parent / FOLDER_ICON_CACHE_DIR_NAME).resolve()
            if path.parent == cache_dir and path.name.startswith(FOLDER_ICON_PREFIX):
                return path
    except OSError:
        return None

    return None


def _remove_previous_cached_folder_icon(folder):
    cached_icon = _generated_cached_icon_path_from_desktop_ini(folder)
    if cached_icon is None or not cached_icon.is_file():
        return False

    try:
        _set_windows_attributes(cached_icon, hidden=False, system=False)
        cached_icon.unlink()
        _remove_empty_icon_cache_dir(cached_icon.parent)
        return True
    except OSError:
        return False


def _remove_empty_icon_cache_dir(cache_dir):
    try:
        if cache_dir.name == FOLDER_ICON_CACHE_DIR_NAME and not any(cache_dir.iterdir()):
            _set_windows_attributes(cache_dir, hidden=False, system=False)
            cache_dir.rmdir()
            return True
    except OSError:
        pass
    return False


def _remove_generated_folder_icon_files(folder):
    removed = False
    for path in folder.glob(f"{FOLDER_ICON_PREFIX}*{FOLDER_ICON_SUFFIX}"):
        if not path.is_file():
            continue
        try:
            _set_windows_attributes(path, hidden=False, system=False)
            path.unlink()
            removed = True
        except OSError:
            pass
    return removed


def _is_generated_desktop_ini(path):
    if not path.is_file():
        return False
    try:
        return DESKTOP_INI_MARKER in path.read_text(encoding="utf-8", errors="ignore")
    except OSError:
        return False


def _set_windows_attributes(path, *, hidden=None, readonly=None, system=None):
    if sys.platform != "win32":
        return False

    try:
        import ctypes

        path_text = str(path)
        kernel32 = ctypes.windll.kernel32
        attrs = kernel32.GetFileAttributesW(path_text)
        if attrs == 0xFFFFFFFF:
            return False

        flags = {
            "readonly": 0x1,
            "hidden": 0x2,
            "system": 0x4,
        }
        updates = {
            "readonly": readonly,
            "hidden": hidden,
            "system": system,
        }
        for name, enabled in updates.items():
            if enabled is True:
                attrs |= flags[name]
            elif enabled is False:
                attrs &= ~flags[name]

        return bool(kernel32.SetFileAttributesW(path_text, attrs))
    except Exception:
        return False
